name: Run Instagram Bot

on:
  schedule:
    - cron: "0 0 * * *"  # Jalan setiap hari jam 00:00 UTC
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Instagram Bot
        run: node instagram_bot.js
        
